-- liquibase formatted sql

-- changeset tokovenko:1
CREATE TABLE users (
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	email VARCHAR(255) NOT NULL UNIQUE,
	first_name VARCHAR(255) NULL,
	last_name VARCHAR(255) NULL,
	phone VARCHAR(12) NULL,
	role INTEGER NULL,
	image TEXT NULL,
	ads INTEGER NULL,
	comments INTEGER NULL,
	PRIMARY KEY (id)
);

-- changeset tokovenko:2
CREATE TABLE ad (
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	author_id INTEGER NULL,
	image TEXT NULL,
	pk INTEGER NULL,
	price INTEGER NULL,
	title VARCHAR(255) NULL,
	description TEXT NULL,
	users_id INTEGER NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (users_id) REFERENCES users(id)
);

-- changeset tokovenko:3
CREATE TABLE comment (
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	author_id INTEGER NULL,
	author_image TEXT NULL,
	author_first_name VARCHAR(255) NULL,
	created_at BIGINT NULL,
	pk INTEGER NULL,
	text TEXT NULL,
	users_id INTEGER NULL,
	ad_id INTEGER NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (users_id) REFERENCES users(id),
	FOREIGN KEY (ad_id) REFERENCES ad(id)
);

-- changeset tokovenko:4
CREATE TABLE login (
	username VARCHAR(255) NOT NULL UNIQUE,
	password VARCHAR(30) NOT NULL,
	PRIMARY KEY (username),
	FOREIGN KEY (username) REFERENCES users(email)
);